name: frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.5
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^9.1.0
  otp_text_field: ^1.1.1
  flutter_secure_storage: ^4.2.0
  http: ^0.13.3
  image_picker: ^0.8.2
  liquid_progress_indicator: ^0.4.0
  firebase_storage: ^10.0.1
  firebase_messaging: ^10.0.4
  firebase_core: ^1.4.0
  permission_handler: ^8.1.4+1
  socket_io_client: ^1.0.1
  email_auth: ^0.0.1+4
  flutter_facebook_auth: ^3.5.0
  flutter_local_notifications: ^8.0.0
  flutter_screenutil: ^5.0.0+2
  encrypt: ^5.0.0
  linkable: ^3.0.1
  url_launcher: ^6.0.9
  flutter_string_encryption: ^0.3.1
  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  receive_sharing_intent: ^1.4.5
  firebase_app_check: ^0.0.1+3
  photo_view: ^0.12.0
  firebase_analytics: ^8.2.0
  tiktoklikescroller: ^0.1.8
  uuid: ^3.0.4
  youtube_player_flutter: ^8.0.0
  swipe_to: 0.0.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/trial.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-VariableFont_wght.ttf
    - family: Merienda
      fonts:
        - asset: fonts/Merienda-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
